apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mysql-pvc
  namespace: sarina-sajjad-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2000M
  storageClassName: hiops
  volumeMode: Filesystem