apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  strategy:
      rollingUpdate:
        maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: quay.io/sarina_ha99/ie_frontend:latest
        imagePullPolicy: Always
        name: frontend
        ports:
          - containerPort: 80
        resources:
            limits:
              memory: "333Mi"
              cpu: "333m"
            requests:
              memory: "333Mi"
              cpu: "333m"
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
        
