apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    http: {
      server {
        listen 3000;
        root /usr/share/nginx/html;
        index index.html index.htm;

        location / {
          try_files $uri $uri/ /index.html;
        }
    }